- id: check-jira-issue
  name: Validate branch name contains a JIRA key
  description: Validate branch name contains a JIRA key; use --username and --password  for JIRA credentials; use --host to specify JIRA server hostname
  entry: check-jira-issue
  language: script
  pass_filenames: false
  always_run: true
- id: prepend-jira-issue
  name: Prepend JIRA issue key
  description: Prepends JIRA issue key to commit msg (if missing)
  entry: prepend-jira-issue
  language: script
  always_run: true
  stages:
    - commit-msg
- id: checkstyle
  name: Checkstyle
  description: Checkstyle
  entry: checkstyle
  language: script
  pass_filenames: true
  types: [text]
- id: detekt
  name: detekt
  description: detekt
  entry: detekt
  language: script
  pass_filenames: false
  files: \.kt$
  require_serial: true
