- id: check-jira-issue
  name: Validate branch name contains a JIRA key
  description: Validate branch name contains a JIRA key; use --username and --password  for JIRA credentials; use --host to specify JIRA server hostname
  entry: check-jira-issue
  language: script
  pass_filenames: false
  always_run: true
- id: append-jira-issue
  name: Append JIRA issue key
  description: Appends the branch's JIRA issue key to the commit msg as a `Refs:` footer (if not already referenced)
  entry: append-jira-issue
  language: script
  always_run: true
  stages:
    - commit-msg
- id: checkstyle
  name: Checkstyle
  description: Checkstyle
  entry: checkstyle
  language: script
  pass_filenames: true
  types: [text]
- id: detekt
  name: detekt
  description: detekt
  entry: detekt
  language: script
  pass_filenames: false
  files: \.kt$
  require_serial: true
- id: ktlint
  name: ktlint
  description: ktlint
  entry: ktlint-script
  language: script
  pass_filenames: true
  files: \.kt$
  require_serial: false
