#!/usr/bin/env bash

BASEDIR="$(dirname "$0")"
if [[ ! -f "$BASEDIR/checkstyle.jar" ]]; then
  curl -sL -o "$BASEDIR/checkstyle.jar" $(curl -s https://api.github.com/repos/checkstyle/checkstyle/releases/latest | jq -r '.assets[].browser_download_url')
fi

java -jar "$BASEDIR/checkstyle.jar" "$@"
