#!/usr/bin/env bash

CONFIG=https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/sun_checks.xml

case $1 in
    -c|--config) CONFIG=$2; shift; shift ;;
esac

java -jar "$(dirname "$0")/checkstyle-8.36-all.jar" -c $CONFIG "$@"
