#!/usr/bin/env bash

BASEDIR="$(dirname "$0")"
if [[ ! -f "$BASEDIR/detekt.jar" ]]; then
  curl -sL -o "$BASEDIR/detekt.jar" $(curl -s https://api.github.com/repos/detekt/detekt/releases/latest | jq -r '.assets[].browser_download_url')
fi

CONFIG="$BASEDIR/detekt.yml"

POSITIONAL=()
while [[ $# -gt 0 ]]
do
  key="$1"

  case $key in
    -c|--config)
    CONFIG="$2"
    shift # past argument
    shift # past value
    ;;
    *) # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift
    ;;
  esac
done

set -- "${POSITIONAL[@]}" # restore positional parameters

if [[ $config == http://* ]] | [[ $config == https://* ]]
then
  curl -sL -o "$BASEDIR/detekt.yml" $config
fi

java --add-opens java.base/java.util=ALL-UNNAMED -jar "$BASEDIR/detekt.jar" -c "$BASEDIR/detekt.yml" "$@"
