#!/usr/bin/env bash

BASEDIR="$(dirname "$0")"
KTLINT_VERSION="1.7.1"

POSITIONAL=()
while [[ $# -gt 0 ]]
do
  key="$1"

  case $key in
    -v)
    KTLINT_VERSION="$2"
    shift # past argument
    shift # past value
    ;;
    *) # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift
    ;;
  esac
done

set -- "${POSITIONAL[@]}" # restore positional parameters

printf "Using ktlint version $KTLINT_VERSION\n"

if [[ ! -f "$BASEDIR/ktlint" ]]; then
  curl -sL -o "$BASEDIR/ktlint" "https://github.com/pinterest/ktlint/releases/download/$KTLINT_VERSION/ktlint"
fi

chmod +x $BASEDIR/ktlint

$BASEDIR/ktlint "$@"
